version: "3.9"
   
services:
  zerotier:
    image: dec0dos/zerotier-controller:latest
    container_name: zerotier-controller
    build:
      context: .
      dockerfile: ./docker/zerotier/Dockerfile
    restart: unless-stopped
    volumes:
      - controller_data:/var/lib/zerotier-one
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"

  db:
    image: postgres:14.2-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    network_mode: "host"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
  postfix:
    image: adepasquale/postfix-catchall
    environment:
      - SMTP_SERVER=localhost
      - SERVER_HOSTNAME=localhost
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - controller_data:/var/lib/zerotier-one
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ZEROTIER_API_KEY=${ZEROTIER_API_KEY}
      - ZEROTIER_NETWORK=${ZEROTIER_NETWORK}
    depends_on:
      - db
      - postfix
      - zerotier

volumes:
  controller_data:
