# Generated by Django 4.0.4 on 2022-05-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_baseconnection_assignedip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseconnection",
            name="assignedIP",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
