# Generated by Django 4.1 on 2022-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_baseconnection_assignedip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseconnection",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="connections",
            field=models.ManyToManyField(to="core.baseconnection"),
        ),
    ]
